### ISSUE TITLE
The app does not seem to play anything

### ISSUE THREAD

**Issue by thetechgeekster** [arma7x/kai-yt-music#1]
Hi! I have an Energizer Energy E241s with KaiOS 2.5.1.1 . I have installed your app via sideloading and BananaHacker's Store. The problem is that although I can find the songs and playlists I want to hear, the MiniPlayer and the Normal Player just stay at 00:00, as it cannot load/stream the songs. Am I doing something wrong of is it the app?

**Comment by arma7x** [comment]
audio/mp4 or audio/webm ?

**Comment by thetechgeekster** [comment]
Both seem to do nothing really. Would you like to send you a screenshot with the problem?

**Comment by arma7x** [comment]
Screenshot not really helpful, I need error/network logs from dev console(via webide). Just tested, I can't reproduce the bug on my Nokia 8110 4G and KaiOS 2.5 Simulator. Can you share the playlist id or song title?

**Comment by piravienthjagdish** [comment]
Hi arma7x,
I have the same problem like @thetechgeekster. I put a link down for a playlist. Just try it out and tell us the result.

Thanks dude for this great app. If this app works well, I will switch definitely my Nokia 6300 to my daily driver.

Greetings from Germany.

Your Piravienth

Playlist: https://youtube.com/playlist?list=PLlrja-fSEv-G_QClSCH1X4Q7SjZlrHtAo

**Comment by arma7x** [comment]
@piravienthjagdish the playlist id is **PLlrja-fSEv-G_QClSCH1X4Q7SjZlrHtAo**. You can use this webapp https://www.the-qrcode-generator.com/ to convert **FREE TEXT** to **QR CODE**

**Comment by piravienthjagdish** [comment]
I already did that but I can't play the songs which I imported

**Comment by arma7x** [comment]
Just debug the playlist on KaiOS Simulator and almost songs in the playlist are not playable due to error code 403(probably geolocked)

**Comment by piravienthjagdish** [comment]
Is there a way to do a workaround?

04.05.2022 20:58:53 Ahmad Malik ***@***.***>:

**Comment by arma7x** [comment]
No

**Comment by piravienthjagdish** [comment]
Does the Nokia 8110 supports VPN (VPN like OpenVPN/Wireguard)?

**Comment by arma7x** [comment]
No. If you need any help regarding KaiOS, ask here https://discord.com/invite/rQ93zEu

**Comment by piravienthjagdish** [comment]
It can't be geoblock because I was at this time in UK and this website says that the video isn't geoblock in any country

Link: https://unblockvideos.com/youtube-video-restriction-checker/#url=N_iW0VC3IdI

**Comment by thetechgeekster** [comment]
@arma7x The playlist is not geoblocked in my area (using my PC) but the player still refuses to play them. Is there any possibility of a problem with the API that is used in the player? In my case I cannot play ANY video. It could be a PEBCAK situation. Could you provide a small tutorial on how to use your app?

**Comment by arma7x** [comment]
YT-Music audio player return error code 403 when it load the media from youtube server

**Comment by thetechgeekster** [comment]
Ok, please try this song (https://www.youtube.com/watch?v=ui8kUKuLBaU). I've just tested in my phone and it does not load it.

**Comment by arma7x** [comment]
> @arma7x The playlist is not geoblocked in my area (using my PC) but the player still refuses to play them. Is there any possibility of a problem with the API that is used in the player? In my case I cannot play ANY video.

**HTTP load failed with status 403**

**Comment by arma7x** [comment]
> Ok, please try this song (https://www.youtube.com/watch?v=ui8kUKuLBaU). I've just tested in my phone and it does not load it.

**HTTP load failed with status 403**

**Comment by thetechgeekster** [comment]
Could you please give us a song/playlist that actually works with the API? Just to make sure it's not our devices/implementations

**Comment by arma7x** [comment]
> Could you please give us a song/playlist that actually works with the API? Just to make sure it's not our devices/implementations

~~https://www.youtube.com/playlist?list=PLo6QvHZ4RyGluhCXRn9MOKNMFwYTFzUBn~~
https://www.youtube.com/playlist?list=PLx0q7abKXxa-HJSGRfHUD1CbexsEqAooN

**Comment by piravienthjagdish** [comment]
I don't know, if this helps out

https://youtu.be/RxN62ZzetwA

Maybe you need multiple API keys in the Music app or 
you have to implement a function where we have to create a new API key for ourselves

**Comment by arma7x** [comment]
YT-Music can fetch the playlist. The issues is the video is unplayable due to 403 error code

**Comment by piravienthjagdish** [comment]
Does the app works with YouTube-DL?
If yes, do you think you can implement a function to clear the cache before and while playing a song?

Sry if I ask too much questions and don't think I'm a developer. I try to find a solution, too 🙂

**Comment by thetechgeekster** [comment]
Maybe this could help. Opened WebIDE for debug. 401 in  https://www.youtube.com/get_video_info
![image](https://user-images.githubusercontent.com/38396429/166816980-a2db354a-1d0d-476c-90af-589783c4f290.png)

**Comment by arma7x** [comment]
> https://www.youtube.com/get_video_info

AFAIK, this endpoint was deprecated. YT Music extract audio/video data from dashManifestUrl(playable) or ytInitialPlayerResponse(403)

**Comment by thetechgeekster** [comment]
My previous comment is wrong. 403 when trying to get audio. I think there might be a change in YT's API, that is why it causes these errors. 
![image](https://user-images.githubusercontent.com/38396429/166817933-d82cf5ab-0059-4b8d-9ae2-e06a85dbc8bb.png)
The song I used, I know for a fact that does not have any geoblocking

**Comment by arma7x** [comment]
I will use https://docs.invidious.io/instances/ to retrieve the audio

**Comment by arma7x** [comment]
@thetechgeekster @piravienthjagdish can you test the latest update(v2.0.1)
https://github.com/arma7x/kai-yt-music/commit/b50bf175e0cfcfe3370c3e185349923d442f3c98

**Comment by thetechgeekster** [comment]
Works perfectly! Thank you @arma7x !!!
