### ISSUE TITLE
questions about the project

### ISSUE THREAD

**Issue by MrDodojo** [arma7x/kai-yt-music#4]
Hi! I am interested in buying a KaiOS phone for listening to music, your project grabbed my attention.
How does this app / project peform? Can it keep playing music if the screen is off? Can it reliably play music in it's current state? What KaiOS version is this made for? Thanks a lot for your time

I'd like to hear back from you, this project will determine if I'll buy a debuggable phone (as I'll need to import it)

**Comment by arma7x** [comment]
quite good and support play audio in background. Only kaios 2.5
