### ISSUE TITLE
"Empty" playlist QR code

### ISSUE THREAD

**Issue by nospamboz** [arma7x/kai-yt-music#5]
Playlist-ID OLAK5uy_l49FDHDzTfCbfdzRlEtLcx_P2Vfr_Xg2U
Generated qr code with https://www.qr-code-generator.com/solutions/text-qr-code/
Scan QR with latest YT music app, results in "Empty"

**Comment by arma7x** [comment]
The scrapping source code was broken, I will fix it when I'm free

**Comment by arma7x** [comment]
fixed, https://github.com/arma7x/kai-yt-music/commit/59aeb54578a98205a7d9b2b9e58c520b2a65d435

**Comment by nospamboz** [comment]
Just tried with both YT and yewtu.be (PLcWeXWZaxWmNTovzjR6IWo6NnCo6EORLd). Still "Empty".

**Comment by arma7x** [comment]
im using onion.tube, PLcWeXWZaxWmNTovzjR6IWo6NnCo6EORLd contains 6 songs
